// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANC_ugeBRrwNRpZxA0usJQfHMfgTgcC1k',
    appId: '1:939544126395:web:1ddec3457bced6c7e29a9e',
    messagingSenderId: '939544126395',
    projectId: 'homeworktracker-390c0',
    authDomain: 'homeworktracker-390c0.firebaseapp.com',
    storageBucket: 'homeworktracker-390c0.firebasestorage.app',
    measurementId: 'G-ZEW6ERX9Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZRmzqg9CLCTjPfQCjh7t-Xypk7RNy0s',
    appId: '1:939544126395:android:e11122f8acb39201e29a9e',
    messagingSenderId: '939544126395',
    projectId: 'homeworktracker-390c0',
    storageBucket: 'homeworktracker-390c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK1S6frXyKh8vWhzWl15FDls8MMnc65gY',
    appId: '1:939544126395:ios:020fa4058cc08461e29a9e',
    messagingSenderId: '939544126395',
    projectId: 'homeworktracker-390c0',
    storageBucket: 'homeworktracker-390c0.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK1S6frXyKh8vWhzWl15FDls8MMnc65gY',
    appId: '1:939544126395:ios:020fa4058cc08461e29a9e',
    messagingSenderId: '939544126395',
    projectId: 'homeworktracker-390c0',
    storageBucket: 'homeworktracker-390c0.firebasestorage.app',
    iosBundleId: 'com.example.homeworkTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANC_ugeBRrwNRpZxA0usJQfHMfgTgcC1k',
    appId: '1:939544126395:web:2cf42327bc5bd847e29a9e',
    messagingSenderId: '939544126395',
    projectId: 'homeworktracker-390c0',
    authDomain: 'homeworktracker-390c0.firebaseapp.com',
    storageBucket: 'homeworktracker-390c0.firebasestorage.app',
    measurementId: 'G-WES8ZEBPGH',
  );
}
